import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import ThemeProvider from "../context/ThemeContext";
import Navbar from "@/components/Home Page/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Navbar></Navbar>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
