import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Navbar from "@/components/Home Page/Navbar";
import ReduxProvider from "@/redux/ReduxProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body suppressHydrationWarning={true}>
        <ReduxProvider>
          {/* <Navbar></Navbar> */}
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
